FROM ruby:2.1
MAINTAINER Richard Attermeyer <richard.attermeyer@gmail.com>

RUN apt-get update \
  && apt-get install -y \
    node \
    python-pygments \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/

RUN gem install \
  github-pages \
  jekyll \
  jekyll-redirect-from \
  kramdown \
  rdiscount \
  rouge

RUN groupadd -g {{group_id}} {{group_name}} && \
  useradd -u {{user_id}} {{user_name}} -g {{group_id}}

VOLUME /src
EXPOSE 4000

USER {{user_name}}
WORKDIR /src
ENTRYPOINT ["jekyll"]
