---
- hosts: localhost
  pre_tasks:
    - name: install required packages
      apt: name="{{item}}" state=present
      with_items:
        - apt-transport-https
  roles:
    - cmprescott.chrome
    - { role: mglaman.atom, atom_user: richard }
    - { role: jekyll, tags: jekyll }
    - { role: virtualbox-guest, virtualbox_x11: True, tags: virtualbox }
    - { role: docker-ubuntu, docker_group_members: richard, tags: docker }
