---
- hosts: localhost
  pre_tasks:
    - name: install required packages
      apt: name="{{item}}" state=present
      with_items:
        - apt-transport-https
        - acl
    - name: Ensure directories exist
      file:
        name: /opt/maven
        state: directory
      tags:
        - maven

  roles:
    - cmprescott.chrome
    - role: angstwad.docker_ubuntu
      docker_pkg_name: "docker-engine=1.11.2-0~xenial"
      pip_version_pip: latest
      pip_version_setuptools: latest
      pip_version_docker_py: latest
      pip_version_docker_compose: latest
      update_docker_package: false
    - role: ansible-oracle-java
      java_version: "{{_java_version}}"
      java_subversion: "{{_java_subversion}}"
      java_install_jce: true
    - role: ansible-role-git
      git:
        user:
          name: "Richard Attermeyer"
          email: "richard.attermeyer@gmail.com"
          account: "{{_user}}"
    - role: ansible-role-vim
      user: richard
      vundle_packages: "{{ vundle_packages_essential | union(vundle_packages_ui)}}"
    - role: tecris.maven
      maven_major: 3
      maven_release: "{{_maven_release}}"
      maven_home_parent_directory: /opt/maven
      tags: maven
    - role: gantsign.intellij
      intellij_default_jdk_home: "/usr/lib/jvm/jdk1.{{_java_version}}.0_{{_java_subversion}}"
      intellij_default_maven_home: "/opt/maven/apache-maven-{{_maven_release}}"
      intellij_edition: ultimate
      users:
        - username: richard
      tags: intellij
    - role: ansible-role-slack
  tasks:
    - name: add maven to path
      lineinfile:
        dest: "/home/{{_user}}/.bashrc"
        line: "export PATH=$PATH:/opt/maven/apache-maven-{{_maven_release}}/bin"
        regexp: "PATH=.*/opt/maven/apache-maven"
        state: present
        insertbefore: "^# Alias definitions"
    - apt:
        name: "pidgin"
        state: present
  post_tasks:
    - name: pin docker-engine version
      template:
        src: templates/docker-engine-pin.j2
        dest: /etc/apt/preferences.d/docker-engine

  environment: "{{proxy_env | default({})}}"

  vars:
    docker_engine_version: "1.11.2-0"
    _java_version: 8
    _java_subversion: 102
    _maven_release: "3.3.9"
    _user: richard

  vars_files:
    - customization.yml
