---
- hosts: localhost
  pre_tasks:
    - name: install required packages
      apt: name="{{item}}" state=present
      with_items:
        - apt-transport-https
        - acl
  roles:
    - cmprescott.chrome
    - role: williamyeh.oracle-java
    - role: ansible-role-git
      git:
        user:
          name: "Richard Attermeyer"
          email: "richard.attermeyer@gmail.com"
          account: richard
    - role: ansible-role-vim
      user: richard
      vundle_packages: "{{ vundle_packages_essential | union(vundle_packages_ui)}}"

  environment: "{{proxy_env | default(omit)}}"

  vars_files:
    - customization.yml
