- src: cmprescott.chrome
  version: 0.2.2
- src: mglaman.atom
  version: 1.0.0
- src: rattermeyer.jekyll-docker
  version: v0.1
- src: rattermeyer.virtualbox-guest
  version: v0.1
- src: rattermeyer.git
  version: v0.3
- src: williamyeh.oracle-java
  version: 2.9.0
- src: gantsign.intellij
  version: 1.0.4
- src: tecris.maven
  version: v1.0.1
